# Render.com deployment configuration
# Place this file in the root of your repository
# Render will automatically detect and use this configuration

services:
  # Backend API Service
  - type: web
    name: submission-api
    env: node
    plan: starter  # Change to 'standard' or 'pro' for production
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    
    # Environment Variables
    # Set these in your Render dashboard under "Environment"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Set this manually in Render dashboard for security
      
    # Auto-deploy settings
    autoDeploy: true  # Deploy automatically when you push to main branch
    
    # Domain settings (optional)
    # domains:
    #   - your-api-domain.com
    
    # Resource limits
    disk:
      name: submission-api-disk
      size: 1GB
      
    # Health check configuration
    healthCheck:
      httpPath: /health
      initialDelaySeconds: 30
      intervalSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3